tasks:
  - name: docker
    openMode: split-left
    command: docker build -t hello-world . && docker run -p 8080:80 hello-world

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8080
    onOpen: open-browser
    visibility: public
